main: me.alexisevelyn.paperwild.Main
name: PaperWild
version: 1.0
api-version: 1.15
author: Alexis Evelyn
description: An Asynchronous Wild Plugin

depend: [42]
softdepend: []

dummy: https://www.spigotmc.org/wiki/plugin-yml/

commands:
    wild:
      description: Warp to a random place
      usage: /wild
      permission: paperwild.command.wild
      default: false
      permission-message: You don't have the paperwild.command.wild permission.
    lagme:
      description: Attempt to lag the server
      usage: /lagme
      permission: paperwild.admin.command.lagme
      default: false
      permission-message: You don't have the paperwild.admin.command.lagme permission.
    loadedchunks:
      description: List loaded chunks
      usage: /loadedchunks
      permission: paperwild.admin.command.loadedchunks
      default: false
      permission-message: You don't have the paperwild.admin.command.loadedchunks permission.
    reload:
      description: Reload Config
      usage: /reload
      permission: paperwild.admin.command.reload
      default: false
      permission-message: You don't have the paperwild.admin.command.reload permission.
